#   █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
#  ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
#  ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝ 
#  ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝  
#  ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║   
#  ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝   
#	gh0stzk - https://github.com/gh0stzk/dotfiles

# import = ["~/.config/alacritty/rice-colors.toml", "~/.config/alacritty/fonts.toml"]
[font]
size = 10.0

[font.bold]
family = "Firacode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Firacode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Firacode Nerd Font"
style = "Italic"

[font.normal]
family = "Firacode Nerd Font"
style = "Regular"

# live_config_reload = true

[cursor]
# blink_interval = 550
# unfocused_hollow = false
# thickness = 0.60

[cursor.style]
blinking = "Never"
# shape = "Beam"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_title = true
opacity = 0.8
dynamic_padding = true

[window.padding]
x = 15
y = 15

[scrolling]
history = 10000
multiplier = 3

[bell]
animation = "Linear"
duration = 0
command = { program = "paplay", args = ["/usr/share/sounds/freedesktop/stereo/dialog-error.oga"] }

[colors.primary]
# background = "#191919"
# background = "#202020"
 background = "#000000"
foreground = "#fff4d2"

[colors.cursor]
text = "#bdae93"
cursor ="#665c54"

[colors.normal]
black = "#1d2021"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#a89984"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#fff4d2"




